seed: 42

DATA:
  product_imgs_dir: /home/master/dataset/test/product_images
  df_products_fn: /home/master/dataset/test/df_products.csv
  df_outfits_fn: /home/master/dataset/test/df_outfits.csv
  cache_dir: processed_data
  imgs_ext: .jpg
  batch_size: 128
  num_workers: 4

INPUT_MODALITY: multimodal  # image or text or multimodal

MODEL_WEIGHTS_PATH: results/best_model_weights.pth

TOKENIZER:
  max_length: 100
  path: results/tokenizer

TEXT_ENCODER:
  pretrained: True
  finetune: False
  finetune_start_block: 5  # there are 0-5 blocks
  l2_norm: True
  projection_size: 1024
  dropout: 0.1

IMAGE_ENCODER:
  pretrained: True
  finetune: False
  finetune_start_block: 7  # there are 0-8 blocks
  l2_norm: True
  projection_size: 1024
  dropout: 0.1

MULTIMODAL_ENCODER:
  embedding_size: 1024
  l2_norm: True
  dropout: 0.1

TRANSFORMS:
  crop: 224
  scale:
    - 0.8
    - 1.0
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
